server:
  host: "localhost"
  port: 3000
  timeouts:
    read: 30s
    write: 30s
    connect: 5s
database:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  timeout: 30s
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  dbname: ${POSTGRES_DB}
logging:
  level: info
  format: json
  file: log/property.log
